# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a21s/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a21s

PRODUCT_COPY_FILES += \
    vendor/samsung/a21s/proprietary/vendor/etc/nfc/sec_s3nrn4v_hwreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nrn4v_hwreg.bin \
    vendor/samsung/a21s/proprietary/vendor/etc/nfc/sec_s3nrn4v_swreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/nfc/sec_s3nrn4v_swreg.bin \
    vendor/samsung/a21s/proprietary/vendor/firmware/nfc/sec_s3nrn4v_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nfc/sec_s3nrn4v_firmware.bin

PRODUCT_PACKAGES += \
    libnfc-sec-vendor
